### ISSUE TITLE
録音できなくなる

### ISSUE THREAD

**Issue by Hykwtakumin** [stkay/GyaonExtension#1]
BrowserActionをクリックしても録音が開始されない
(恐らくMediaRecorderへのコンテキストが失われている?)

- 例外処理を実装する
- MediaRecorderへのアクセスを確実にする

**Comment by Hykwtakumin** [comment]
とりあえず何かあったらオプション画面からすぐにリロードできるようにはした

**Comment by Hykwtakumin** [comment]
Error in event handler for browserAction.onClicked: UnknownError: Failed to execute 'start' on 'MediaRecorder': The MediaRecorder failed to start because there are no audio or video tracks available.
    at startRecording (chrome-extension://ehcdlihfcfflfcejdajmjgdnldcpkdpd/scripts/background.js:189:18)
    at chrome-extension://ehcdlihfcfflfcejdajmjgdnldcpkdpd/scripts/background.js:232:9
